apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-batch-cronjob-config
data:
  application.properties: |
    application.title=spring-batch-cronjob
    expanded.project.version=@project.version@
    
    spring.application.name=spring-batch-cronjob

    spring.data.mongodb.uri=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo-dev:27017
    spring.data.mongodb.database=cronJob
