apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - cronjob.yaml
  - configmap.yaml
  - hpa.yaml
  - secret.yaml
  - ingress.yaml
patches:
  - path: ./patches/rollouts.yaml

transformers:
  - ./kustomizeconfig/namesuffixtransformer.yaml
  - ./kustomizeconfig/dd-transformer.yaml

images:
  - name: IMAGE_NAME/PATH:TAG
    newName: spring-batch-cronjob
    newTag: latest

labels:
  - includeSelectors: true
    pairs:
      app: spring-batch-cronjob
