apiVersion: batch/v1
kind: CronJob
metadata:
  name: spring-batch-cronjob
  namespace: default
spec:
  schedule: "*/1 * * * *" # A cada 5 minutos
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: spring-batch
              image: iosilva/spring-batch-cronjob:latest
              imagePullPolicy: Always
          restartPolicy: OnFailure
